name: 0afr Action

on:
  schedule:
    - cron: '11 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "0afr Bot"
      
      - name: updating 0afr
        run: sh ressources/frtv/py/0afr2345.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "0afr Updated"
          git push
