name: 0tf

on:
  schedule:
    - cron: '48 */3 * * *'
  push:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  inject_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout freeiptv
        uses: actions/checkout@v3
        
      - name: Fetch Content
        id: fetch_content
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          content=$(curl -H "Authorization: token $PRIVATE_REPO_TOKEN" -H "Accept: application/vnd.github.v3.raw" "https://raw.githubusercontent.com/ipstreet312/myrep/main/ressources/tfphd.m3u8")
          echo "${content}" > all.m3u

      - name: Replace Text
        if: steps.fetch_content.outputs.content != ''
        run: |
          content="${{ steps.fetch_content.outputs.content }}"
          content_escaped=$(echo "$content" | sed 's/[\/&]/\\&/g')
          sed -i "/tf1-cmaf/ c ${content_escaped}" all.m3u
    
      - name: Commit and Push Changes
        run: |
          git config --local user.name "0tf Action"
          git config user.email "<>"
          git pull origin main
          git add all.m3u
          git commit -m "0tf updated"
          git push origin main
