name: auftanken

on:
  schedule:
    - cron: '00 */12 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "auftanken bot"
      
      - name: grab m3u files
        run: python3 ressources/infos/barkers/auftanken.py
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "auftanken updated"
          git push
