name: dmdirectprx

on:
  schedule:
    - cron: '33 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "dmdirectprx bot"
      
      - name: grab m3u files
        run: |
          export http_proxy="http://20.111.54.16:8123"
          export https_proxy="http://20.111.54.16:8123"
          python3 ressources/dmotion/py/dmdirect/dmdirectprx.py
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "dmdirectprx updated"
          git push origin master
