name: equi
on:
  schedule:
    - cron: '00 */4 * * *'
  workflow_dispatch:
  
jobs:
  Update-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: update equi
        run: sh ./feed/equi.sh

      - name: setup git config
        run: |
          git config user.name "Equi Bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git pull
          git add ./feed/equi.m3u8
          git commit -m "Update-build"
          git push origin master
