name: k12a action

on:
  schedule:
    - cron: '00 */18 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "k12a bot"
      
      - name: updating k12a
        run: sh ressources/keshetil/py/k12a.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "k12a updated"
          git push
