name: nowturkmaster action

on:
  schedule:
    - cron: '30 */3 * * *'
  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowturkmaster bot"
      
      - name: updating nowturkmaster
        run: python3 ressources/tur/nowturkmaster.py > ressources/tur/nowturkmaster.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "nowturkmaster updated"
          git push origin master
