name: nowtvtrfork

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtvtrfork bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: Fetch content nowtvtr
        id: fetch_content
        run: |
          final_url=$(python3 ressources/tur/nowtvtr.py)
          echo "::set-output name=erstrm::$(echo $final_url | awk 'NR==1')"
          echo "::set-output name=donstrm::$(echo $final_url | awk 'NR==2')"

      - name: Replace Text
        run: |
          erstrm="${{ steps.fetch_content.outputs.erstrm }}"
          donstrm="${{ steps.fetch_content.outputs.donstrm }}"
          sed -i "s|nowtv-live-ad.ercdn.net/nowtv|${erstrm}|g" ressources/tur/nowtvtr.txt
          sed -i "s|nowtv.daioncdn.net/nowtv|${donstrm}|g" ressources/tur/nowtvtr.txt

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add ressources/tur/nowtvtr.txt
          git commit -m "nowtvtrfork updated"
          git push
