name: nowtest

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtest bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: fetch content nowtest
        run: |
          python3 ressources/tur/nowtest.py > temp.txt
          source temp.txt
          echo "${erstrm}${dastrm}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          sed -i "s|https://nowtv-live-ad\.ercdn\.net/nowtv/playlist\.m3u8\?st=.*&e=[0-9]+|${erstrm}|g" ressources/tur/nowtest.m3u
          sed -i "s|https://nowtv\.daioncdn\.net/nowtv/nowtv\.m3u8\?st=.*&e=[0-9]+|${dastrm}|g" ressources/tur/nowtest.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add ressources/tur/nowtest.m3u
          git commit -m "nowtest updated"
          git push
