name: nowtvtrfork

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtvtrfork bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: fetch content nowtvtrfork
        run: |
          final_string=$(python3 ressources/tur/nowtvtr.py)
          echo "final_url=${final_string}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          query_string=$(echo "${final_string}" | cut -d'?' -f2)
          sed -i "s|https://nowtv-live-ad.ercdn.net/nowtv/playlist.m3u8?.*|https://nowtv-live-ad.ercdn.net/nowtv/playlist.m3u8?${query_string}|g" ressources/tur/nowtvtr.txt

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add ressources/tur/nowtvtr.txt
          git commit -m "nowtvtrfork updated"
          git push
