name: nowtvtrfork

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nowtvtrfork bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: Fetch content nowtvtr
        id: fetch_content
        run: |
          final_urls=$(python3 ressources/tur/nowtvtr.py)
          echo "erstrm=$(echo $final_urls | awk 'NR==1')" >> $GITHUB_ENV
          echo "donstrm=$(echo $final_urls | awk 'NR==2')" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          sed -i "s|nowtv-live-ad.ercdn.net/nowtv|${{ env.erstrm }}|g" ressources/tur/nowtvtr.txt
          sed -i "s|nowtv.daioncdn.net/nowtv|${{ env.donstrm }}|g" ressources/tur/nowtvtr.txt

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add ressources/tur/nowtvtr.txt
          git commit -m "nowtvtrfork updated"
          git push
