name: one action

on:
  schedule:
    - cron: '10 */10 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "one bot"
      
      - name: updating one
        run: python3 ressources/mde/one.py > ressources/mde/one.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "one updated"
          git push origin master
