name: streamlinkfox

on:
  schedule:
    - cron: '03 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "streamlinkfox bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests streamlink

      - name: Fetch customized streamlinkfox plugin
        run: |
          git remote add forked_repo https://github.com/ipstreet312/streamlink.git
          git fetch forked_repo
          git checkout patch-1
      
      - name: Change directory to freeiptv
        run: cd freeiptv/ressources/tur

      - name: Generate nowtv.m3u8
        run: python3 streamlinkfox.py > nowtv.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "nowtv updated"
          git push     
