name: testnow
on:
  schedule:
    - cron: "00 04,16 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Install streamlink module from forked repository
        run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: updating testnow
        run: sh ressources/tur/test.sh "$(python ressources/tur/test.py | head -n 1)" "$(python ressources/tur/test.py | tail -n 1)"

      - name: setup git config
        run: |
          git config user.name "testnow bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git pull
          git add ressources/tur/test.m3u
          git commit -m "testnow updated"
          git push
