name: tvi-pt_ch action
on:
  schedule:
    - cron: "00 04,16 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating tvi-pt_ch
        run: |
          chmod +x ressources/tvipt/sh/tviptch.sh
          ./ressources/tvipt/sh/tviptch.sh

      - name: setup git config
        run: |
          git config user.name "tvi-pt_ch bot"
          git config user.email "<>"

      - name: Git add
        run: |
          git add -A
          git status

      - name: Commit changes
        run: git commit -m "tvi-pt_ch updated"

      - name: Push changes
        run: git push
